[2025-03-24T17:31:05.552-1000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T17:31:05.555-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:30:59.761790+00:00 [queued]>
[2025-03-24T17:31:05.557-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:30:59.761790+00:00 [queued]>
[2025-03-24T17:31:05.557-1000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-24T17:31:05.559-1000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): train_model_task> on 2025-03-25 03:30:59.761790+00:00
[2025-03-24T17:31:05.565-1000] {standard_task_runner.py:72} INFO - Started process 42991 to run task
[2025-03-24T17:31:05.567-1000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'titanic', 'train_model_task', 'manual__2025-03-25T03:30:59.761790+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/titanic_airflow.py', '--cfg-path', '/var/folders/m_/z_1_g7ln0f54m3f57y9mjg440000gn/T/tmpfqr2oj1e']
[2025-03-24T17:31:05.568-1000] {standard_task_runner.py:105} INFO - Job 21: Subtask train_model_task
[2025-03-24T17:31:05.582-1000] {task_command.py:467} INFO - Running <TaskInstance: titanic.train_model_task manual__2025-03-25T03:30:59.761790+00:00 [running]> on host mac.localdomain
[2025-03-24T17:31:05.597-1000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T03:30:59.761790+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T03:30:59.761790+00:00'
[2025-03-24T17:31:05.597-1000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-24T17:31:05.597-1000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-24T17:31:05.598-1000] {logging_mixin.py:190} INFO - Current task name:train_model_task state:running start_date:2025-03-25 03:31:05.555663+00:00
[2025-03-24T17:31:05.598-1000] {logging_mixin.py:190} INFO - Dag name:titanic and current dag run status:running
[2025-03-24T17:31:05.598-1000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T17:31:06.028-1000] {logging_mixin.py:190} INFO - knn: 0.8827751196172249
[2025-03-24T17:31:06.031-1000] {logging_mixin.py:190} INFO - üèÉ View run knn at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/2d6db03d601f4b0d8a9fcfebbd184153
[2025-03-24T17:31:06.031-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:06.038-1000] {logging_mixin.py:190} INFO - decision_tree: 0.8205741626794258
[2025-03-24T17:31:06.040-1000] {logging_mixin.py:190} INFO - üèÉ View run decision_tree at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/fcaed367f61a4748b07f75fda738c6a5
[2025-03-24T17:31:06.041-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:06.048-1000] {logging_mixin.py:190} INFO - random_forest: 0.8444976076555024
[2025-03-24T17:31:06.050-1000] {logging_mixin.py:190} INFO - üèÉ View run random_forest at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/6574340d5b7d4ba680386490d1723030
[2025-03-24T17:31:06.050-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:06.057-1000] {logging_mixin.py:190} INFO - gaussian: 0.8421052631578947
[2025-03-24T17:31:06.059-1000] {logging_mixin.py:190} INFO - üèÉ View run gaussian at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/676ca91d07564af0b7afbc990108fb2d
[2025-03-24T17:31:06.059-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:06.066-1000] {logging_mixin.py:190} INFO - svc: 0.9354066985645934
[2025-03-24T17:31:06.069-1000] {logging_mixin.py:190} INFO - üèÉ View run svc at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/3106f2ef111e4f5db0c35f2d2daf0cff
[2025-03-24T17:31:06.069-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:06.075-1000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 71, in train_model_task
    mlflow.register_model(f"runs:/{model_dict[model_name]}/model", model_dict[model_name])
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 80, in register_model
    return _register_model(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 95, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/client.py", line 3564, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/client.py", line 68, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/model_registry/rest_store.py", line 80, in create_registered_model
    CreateRegisteredModel(name=name, tags=proto_tags, description=description)
TypeError: bad argument type for built-in operation
[2025-03-24T17:31:06.080-1000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-24T17:31:06.080-1000] {logging_mixin.py:190} INFO - Task start:2025-03-25 03:31:05.555663+00:00 end:2025-03-25 03:31:06.080506+00:00 duration:0.524843
[2025-03-24T17:31:06.080-1000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): train_model_task> dag:<DAG: titanic> dagrun:<DagRun titanic @ 2025-03-25 03:30:59.761790+00:00: manual__2025-03-25T03:30:59.761790+00:00, state:running, queued_at: 2025-03-25 03:30:59.764252+00:00. externally triggered: True>
[2025-03-24T17:31:06.081-1000] {logging_mixin.py:190} INFO - Failure caused by bad argument type for built-in operation
[2025-03-24T17:31:06.081-1000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic, task_id=train_model_task, run_id=manual__2025-03-25T03:30:59.761790+00:00, execution_date=20250325T033059, start_date=20250325T033105, end_date=20250325T033106
[2025-03-24T17:31:06.085-1000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T17:31:06.085-1000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task train_model_task (bad argument type for built-in operation; 42991)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 71, in train_model_task
    mlflow.register_model(f"runs:/{model_dict[model_name]}/model", model_dict[model_name])
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 80, in register_model
    return _register_model(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 95, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/client.py", line 3564, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/client.py", line 68, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/model_registry/rest_store.py", line 80, in create_registered_model
    CreateRegisteredModel(name=name, tags=proto_tags, description=description)
TypeError: bad argument type for built-in operation
[2025-03-24T17:31:06.114-1000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T17:31:06.120-1000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T17:31:06.121-1000] {local_task_job_runner.py:245} INFO - ::endgroup::
