[2025-03-24T17:31:23.786-1000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T17:31:23.789-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:26:16.755303+00:00 [queued]>
[2025-03-24T17:31:23.791-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:26:16.755303+00:00 [queued]>
[2025-03-24T17:31:23.791-1000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-24T17:31:23.794-1000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): train_model_task> on 2025-03-25 03:26:16.755303+00:00
[2025-03-24T17:31:23.799-1000] {standard_task_runner.py:72} INFO - Started process 43080 to run task
[2025-03-24T17:31:23.801-1000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'titanic', 'train_model_task', 'manual__2025-03-25T03:26:16.755303+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/titanic_airflow.py', '--cfg-path', '/var/folders/m_/z_1_g7ln0f54m3f57y9mjg440000gn/T/tmp1by9xos_']
[2025-03-24T17:31:23.802-1000] {standard_task_runner.py:105} INFO - Job 22: Subtask train_model_task
[2025-03-24T17:31:23.818-1000] {task_command.py:467} INFO - Running <TaskInstance: titanic.train_model_task manual__2025-03-25T03:26:16.755303+00:00 [running]> on host mac.localdomain
[2025-03-24T17:31:23.833-1000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T03:26:16.755303+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T03:26:16.755303+00:00'
[2025-03-24T17:31:23.834-1000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-24T17:31:23.834-1000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-24T17:31:23.834-1000] {logging_mixin.py:190} INFO - Current task name:train_model_task state:running start_date:2025-03-25 03:31:23.789745+00:00
[2025-03-24T17:31:23.834-1000] {logging_mixin.py:190} INFO - Dag name:titanic and current dag run status:running
[2025-03-24T17:31:23.835-1000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T17:31:24.301-1000] {logging_mixin.py:190} INFO - knn: 0.8827751196172249
[2025-03-24T17:31:24.304-1000] {logging_mixin.py:190} INFO - üèÉ View run knn at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/d896b5d8aee94a99adb8838da408c27d
[2025-03-24T17:31:24.304-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:24.312-1000] {logging_mixin.py:190} INFO - decision_tree: 0.8157894736842105
[2025-03-24T17:31:24.315-1000] {logging_mixin.py:190} INFO - üèÉ View run decision_tree at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/b455e3a31e7240a69a8f5358f0401e56
[2025-03-24T17:31:24.315-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:24.322-1000] {logging_mixin.py:190} INFO - random_forest: 0.8229665071770335
[2025-03-24T17:31:24.325-1000] {logging_mixin.py:190} INFO - üèÉ View run random_forest at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/6df12bbda90f4eeaab65d513b82edd8f
[2025-03-24T17:31:24.325-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:24.333-1000] {logging_mixin.py:190} INFO - gaussian: 0.8421052631578947
[2025-03-24T17:31:24.335-1000] {logging_mixin.py:190} INFO - üèÉ View run gaussian at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/2e3812a9130d4b7b85d45d5057d869c8
[2025-03-24T17:31:24.335-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:24.343-1000] {logging_mixin.py:190} INFO - svc: 0.9354066985645934
[2025-03-24T17:31:24.345-1000] {logging_mixin.py:190} INFO - üèÉ View run svc at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/f251cc166da142148173e06e0fd3dbf6
[2025-03-24T17:31:24.345-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:31:24.351-1000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 71, in train_model_task
    mlflow.register_model(f"runs:/{model_dict[model_name]}/model", model_dict[model_name])
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 80, in register_model
    return _register_model(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 95, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/client.py", line 3564, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/client.py", line 68, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/model_registry/rest_store.py", line 80, in create_registered_model
    CreateRegisteredModel(name=name, tags=proto_tags, description=description)
TypeError: bad argument type for built-in operation
[2025-03-24T17:31:24.356-1000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-24T17:31:24.356-1000] {logging_mixin.py:190} INFO - Task start:2025-03-25 03:31:23.789745+00:00 end:2025-03-25 03:31:24.356299+00:00 duration:0.566554
[2025-03-24T17:31:24.356-1000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): train_model_task> dag:<DAG: titanic> dagrun:<DagRun titanic @ 2025-03-25 03:26:16.755303+00:00: manual__2025-03-25T03:26:16.755303+00:00, state:running, queued_at: 2025-03-25 03:26:16.759561+00:00. externally triggered: True>
[2025-03-24T17:31:24.357-1000] {logging_mixin.py:190} INFO - Failure caused by bad argument type for built-in operation
[2025-03-24T17:31:24.357-1000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=titanic, task_id=train_model_task, run_id=manual__2025-03-25T03:26:16.755303+00:00, execution_date=20250325T032616, start_date=20250325T033123, end_date=20250325T033124
[2025-03-24T17:31:24.363-1000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T17:31:24.364-1000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task train_model_task (bad argument type for built-in operation; 43080)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 71, in train_model_task
    mlflow.register_model(f"runs:/{model_dict[model_name]}/model", model_dict[model_name])
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 80, in register_model
    return _register_model(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 95, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/client.py", line 3564, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/client.py", line 68, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/model_registry/rest_store.py", line 80, in create_registered_model
    CreateRegisteredModel(name=name, tags=proto_tags, description=description)
TypeError: bad argument type for built-in operation
[2025-03-24T17:31:24.389-1000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T17:31:24.394-1000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T17:31:24.394-1000] {local_task_job_runner.py:245} INFO - ::endgroup::
