[2025-03-24T17:26:21.707-1000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T17:26:21.710-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:26:16.755303+00:00 [queued]>
[2025-03-24T17:26:21.712-1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.train_model_task manual__2025-03-25T03:26:16.755303+00:00 [queued]>
[2025-03-24T17:26:21.712-1000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-24T17:26:21.714-1000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): train_model_task> on 2025-03-25 03:26:16.755303+00:00
[2025-03-24T17:26:21.719-1000] {standard_task_runner.py:72} INFO - Started process 41788 to run task
[2025-03-24T17:26:21.722-1000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'titanic', 'train_model_task', 'manual__2025-03-25T03:26:16.755303+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/titanic_airflow.py', '--cfg-path', '/var/folders/m_/z_1_g7ln0f54m3f57y9mjg440000gn/T/tmp6oksgjrr']
[2025-03-24T17:26:21.722-1000] {standard_task_runner.py:105} INFO - Job 18: Subtask train_model_task
[2025-03-24T17:26:21.735-1000] {task_command.py:467} INFO - Running <TaskInstance: titanic.train_model_task manual__2025-03-25T03:26:16.755303+00:00 [running]> on host mac.localdomain
[2025-03-24T17:26:21.750-1000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T03:26:16.755303+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T03:26:16.755303+00:00'
[2025-03-24T17:26:21.751-1000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-24T17:26:21.751-1000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-24T17:26:21.751-1000] {logging_mixin.py:190} INFO - Current task name:train_model_task state:running start_date:2025-03-25 03:26:21.710761+00:00
[2025-03-24T17:26:21.751-1000] {logging_mixin.py:190} INFO - Dag name:titanic and current dag run status:running
[2025-03-24T17:26:21.751-1000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T17:26:22.189-1000] {logging_mixin.py:190} INFO - knn: 0.8827751196172249
[2025-03-24T17:26:22.191-1000] {logging_mixin.py:190} INFO - üèÉ View run knn at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/e573a9756a134bd48e4f7d27628121a7
[2025-03-24T17:26:22.191-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:26:22.199-1000] {logging_mixin.py:190} INFO - decision_tree: 0.8110047846889952
[2025-03-24T17:26:22.201-1000] {logging_mixin.py:190} INFO - üèÉ View run decision_tree at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/033b7ffcb3b74d04afaf4ad913cbde46
[2025-03-24T17:26:22.202-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:26:22.209-1000] {logging_mixin.py:190} INFO - random_forest: 0.8373205741626795
[2025-03-24T17:26:22.211-1000] {logging_mixin.py:190} INFO - üèÉ View run random_forest at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/fba47611744f4c3a95d2f26f5c41e4d1
[2025-03-24T17:26:22.211-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:26:22.219-1000] {logging_mixin.py:190} INFO - gaussian: 0.8421052631578947
[2025-03-24T17:26:22.221-1000] {logging_mixin.py:190} INFO - üèÉ View run gaussian at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/963d55f1ee834cec8dd8b26eb98f2635
[2025-03-24T17:26:22.221-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:26:22.228-1000] {logging_mixin.py:190} INFO - svc: 0.9354066985645934
[2025-03-24T17:26:22.230-1000] {logging_mixin.py:190} INFO - üèÉ View run svc at: http://127.0.0.1:5000/#/experiments/465029726783557625/runs/d2f7e109e6d64ddc991e48c96d085170
[2025-03-24T17:26:22.230-1000] {logging_mixin.py:190} INFO - üß™ View experiment at: http://127.0.0.1:5000/#/experiments/465029726783557625
[2025-03-24T17:26:22.238-1000] {logging_mixin.py:190} WARNING - Successfully registered model 'svc'.
[2025-03-24T17:26:22.239-1000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 70, in train_model_task
    mlflow.register_model(f"runs:/{model_dict[model_name]}/model", model_name)
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 80, in register_model
    return _register_model(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 111, in _register_model
    source = RunsArtifactRepository.get_underlying_uri(model_uri)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 39, in get_underlying_uri
    uri = get_artifact_uri(run_id, artifact_path, tracking_uri)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/artifact_utils.py", line 52, in get_artifact_uri
    run = store.get_run(run_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 177, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 392, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 249, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid value "SVC()" for parameter 'run_id' supplied.
[2025-03-24T17:26:22.246-1000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-24T17:26:22.246-1000] {logging_mixin.py:190} INFO - Task start:2025-03-25 03:26:21.710761+00:00 end:2025-03-25 03:26:22.246178+00:00 duration:0.535417
[2025-03-24T17:26:22.246-1000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): train_model_task> dag:<DAG: titanic> dagrun:<DagRun titanic @ 2025-03-25 03:26:16.755303+00:00: manual__2025-03-25T03:26:16.755303+00:00, state:running, queued_at: 2025-03-25 03:26:16.759561+00:00. externally triggered: True>
[2025-03-24T17:26:22.246-1000] {logging_mixin.py:190} INFO - Failure caused by INVALID_PARAMETER_VALUE: Invalid value "SVC()" for parameter 'run_id' supplied.
[2025-03-24T17:26:22.246-1000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic, task_id=train_model_task, run_id=manual__2025-03-25T03:26:16.755303+00:00, execution_date=20250325T032616, start_date=20250325T032621, end_date=20250325T032622
[2025-03-24T17:26:22.251-1000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T17:26:22.251-1000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task train_model_task (INVALID_PARAMETER_VALUE: Invalid value "SVC()" for parameter 'run_id' supplied.; 41788)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manamioyama/Desktop/workspace/GA/ml_playground/ml_playground_test/manami/airflow/dags/titanic_airflow.py", line 70, in train_model_task
    mlflow.register_model(f"runs:/{model_dict[model_name]}/model", model_name)
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 80, in register_model
    return _register_model(
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/_model_registry/fluent.py", line 111, in _register_model
    source = RunsArtifactRepository.get_underlying_uri(model_uri)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 39, in get_underlying_uri
    uri = get_artifact_uri(run_id, artifact_path, tracking_uri)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/tracking/artifact_utils.py", line 52, in get_artifact_uri
    run = store.get_run(run_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 177, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 90, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 392, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 249, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid value "SVC()" for parameter 'run_id' supplied.
[2025-03-24T17:26:22.268-1000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T17:26:22.274-1000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T17:26:22.275-1000] {local_task_job_runner.py:245} INFO - ::endgroup::
